language: python
python:
  - "3.6"
env:
  global:
    - SLUGIFY_USES_TEXT_UNIDECODE=yes
install:
  - "make setup-dev"
  - "make venv"
  - "pip install coveralls"
script:
  - "make test"
after_success:
  - coveralls
