language: python
python:
  - "3.6"
env:
  global:
    - SLUGIFY_USES_TEXT_UNIDECODE=yes
install:
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"
  - "pipenv install coveralls"
script:
  - "pipenv run pytest tests -p no:warnings --verbose --color=yes"
after_success:
- coveralls